### ISSUE TITLE
I have a very difficult problem

### ISSUE THREAD

**Issue by MenFsq** [upsetjs/upsetjs#104]
```
const elems = [
  { name: 'A', sets: ['S1', 'S2'] },
  { name: 'B', sets: ['S1'] },
  { name: 'C', sets: ['S2'] },
  { name: 'D', sets: ['S1', 'S3'] },
];
```
Hello, how do I only display B data containing S1 on upsetJS?

**Comment by sgratzl** [comment]
...
const { sets, combinations } = extractCombinations(elems);
```
will return the sets and combinations that are fed into UpSet.js. You could just filter those two arrays according to your needs

**Comment by MenFsq** [comment]
> ```js
> ...
>  const  {集合，组合}  =  extractCombinations ( elems ) ;
> ```
> 
> 将返回输入 UpSet.js 的集合和组合。您可以根据需要过滤这两个数组

**Comment by MenFsq** [comment]
Thank you very much for answering my question in your busy schedule.    I may not have described my question clearly.    In the returned set and combination, there is no option B containing only S1, but there are three data containing S1 I want to render the one with only one S1 on the upset diagram (that is, how to clearly reflect the data of Name is B on the upset diagram)

**Comment by sgratzl** [comment]
Sorry, I don't understand your question. can you create a sketch or based on the example of yours the subset of data you want to achieve?
