### ISSUE TITLE
Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)

### ISSUE THREAD

**Issue by va1erie** [upsetjs/upsetjs#115]
When I use the Histogram import in react 18.0.0: _import {Histogram} from '@upsetjs/plots';_ for creating a Histogram, like the first example [here](https://upset.js.org/docs/plots/histogram), I get the following error:
**ERROR in ./node_modules/vega/index.js 17:0-41
Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)**

However, the Histogram is created and when you close the error in the browser, the histogram works.

**My solution**

- in ./node_modules/vega/index.js change _export {version} from './package.json';_  to  _export * as packageInfo from 'package.json'_
- in ./node_modules/vega/package.json change _"version": "5.22.1",_  to   _"version": "packageInfo.version",_
After these two changes the Histogram works and no error is thrown.

**Context**

- Version: react.js 18.0.0, upsetjs/plots: 1.11.0, upsetjs/react: 1.11.0
- Browser: Firefox
- OS : Windows 10

**Comment by sgratzl** [comment]
this library is only using the `vega` library but doesn't control it. It seems like this issue is better suited in vega then
