### ISSUE TITLE
 The "fill: transparent" attribute in the SVG resulting image source code is not recognized by the AI drawing tool and must be replaced with "fill: none"

### ISSUE THREAD

**Issue by Jiahe-Sun** [upsetjs/upsetjs#134]
Hi,

We checked and found that the SVG result image exported by the UpsetJS package showed garbled characters in the AI graphics editing tool (as shown below). The check found that the AI drawing tool could not recognize the plugin "fill: transparent "graphic transparency property, we hope you can make adjustments to avoid this problem.

Garbled image:
<img width="1440" alt="image" src="https://github.com/upsetjs/upsetjs/assets/69581197/78daf3a6-e2e8-44dd-b7a9-f486bec0bba5">

After modifying the "fill: transparent" attribute in the SVG source code to the "fill: none" attribute:
<img width="1440" alt="image" src="https://github.com/upsetjs/upsetjs/assets/69581197/6db27050-e4dc-401f-adbd-d85fb6982a5d">
<img width="1166" alt="image" src="https://github.com/upsetjs/upsetjs/assets/69581197/222aaf16-3878-4ca1-9050-db23b5b04564">

**Comment by sgratzl** [comment]
I cannot use `fill: none` since then the user cannot click those rects anymore but it is required for interaction. With `fill: transparent` it works fine and browsers have no problem rendering it.
