### ISSUE TITLE
Option to exclude horizontal set bar plot

### ISSUE THREAD

**Issue by dleopold** [upsetjs/upsetjs#135]
It would be great if there was an option to exclude the horizontal set bar plot. I am currently developing data exploration app that includes an upset module. I would like to reduce any unnecessary elements to reduce clutter (there is already a lot going on in the app).  Since the information in the horizontal plot is already included in the main plot, I would like to suppress it. Perhaps I am missing something in the docs pertaining to this, but I did not find a relevant option. If it is not an option, maybe there is a simple workaround?

**Comment by sgratzl** [comment]
you can use the https://upset.js.org/api/react/interfaces/UpSetLayoutProps.html#widthRatios options to specify the width of individual components. 

e.g.
![image](https://github.com/upsetjs/upsetjs/assets/4129778/6a36a78e-6e42-43d0-9f96-298fb78f43da)
