### ISSUE TITLE
UpsetJS in spotfire

### ISSUE THREAD

**Issue by aparente-nurix** [upsetjs/upsetjs#37]
I've used static upset plots and have been looking for more interactive functionality. I'm curious if anyone has tried to get upsetjs into spotfire, that way data tables of giant datasets can't be linked and multiple other visualizations can be added.

**Comment by sgratzl** [comment]
I tried but I don't have an spotfire license. There is https://community.tibco.com/wiki/javascript-visualization-framework-jsviz-and-tibco-spotfire which could be  starting point. 

However, there are integrations for [Tableau](https://upset.js.org/integrations/tableau/) and [PowerBI](https://upset.js.org/integrations/powerbi/)
