### ISSUE TITLE
the upset chart was stuck and difficult to see

### ISSUE THREAD

**Issue by vongmengty** [upsetjs/upsetjs#93]
the chart was stuck and difficult to see.
I can not find the upset2 sample.
Can you give me some advise about upset2 with js please?

**upset2**
![image](https://user-images.githubusercontent.com/19471093/146698295-5f0f9952-8ebe-4adb-bdd1-e2a36f21e7e4.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/19471093/146697941-f561232b-4d1f-41f9-b66f-cc2f9373518d.png)

**Comment by sgratzl** [comment]
this is upset.js a re-implentation of upsetR, so it will never look like upset2. 

Just to clarify you want to compute of 12 sets all possible combinations?

**Comment by vongmengty** [comment]
yes, I want compute of 12 sets, but the chart was stuck.

my data: 
`[
  {
    "name": "4c0e0aa0-65f3-4f6b-bdcc-a2ae6b0c0f31",
    "sets": [
        "Grade 7",
    ]
},
{
    "name": "baf47555-b8d0-4651-9597-dfc569818d94",
    "sets": [
        "Grade 1",
        "Grade 2",
        "Grade 3",
      "Grade 4",
      "Grade 5",
      "Grade 6",
      "Grade 7",
      "Grade 8",
      "Grade 9",
      "Grade 10",
      "Grade 11",
      "Grade 12",
    ]
},
{
    "name": "0dbe440a-c458-40d4-b216-ca0902aa76aa",
    "sets": [
        "Grade 6",
        "Grade 9",
    ]
},
]`
as I log I see combination have 4095 and the browser always stuck and auto run debug.
![image](https://user-images.githubusercontent.com/19471093/146856395-a5c86a44-b973-4915-8fae-daf17a8312b5.png)

**Comment by sgratzl** [comment]
are you looking for the distinct combinations or all possible combinations?

Moreover, have you tried using the `extractCombinations` method, https://github.com/upsetjs/upsetjs/blob/main/packages/model/src/data/extractCombinations.ts#L88 which is more optimized

**Comment by vongmengty** [comment]
I'm looking for all possible combinations.
I had used the extractCombinations method, but the upset chart show like above.

Can the upsetjs do the chart like that link https://vdl.sci.utah.edu/upset2/ ?
if can, Can you give me some example please?

because of some my data lots than 12sets.

**Comment by sgratzl** [comment]
wontfix stale
