### ISSUE TITLE
Allow specifying a CSP `nonce` to injected style tags

### ISSUE THREAD

**Issue by emi-samoscyber** [upsetjs/upsetjs#97]
HTTP [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) (CSP) _style-src_ directive specifies the valid sources for stylesheets. A common setting involves not including ´'unsafe-inline'´ to avoid certain XSS vectors.

Since UpSet.js components use injected style tags to customize the plots, they get blocked when a strict CSP directive is specified.
![image](https://user-images.githubusercontent.com/66857125/154765425-c145d0a7-5d8f-4291-82d1-b34c47d80dc0.png)
_Note: The red lines are just manually redacted text in the screenshot_

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
The injected style tags are dynamic, so it's impossible to specify a whitelisted content hash for them.

A solution for this issue would be using the arbitrary nonce whitelisting, where the server will generate a random string and UpSet.js components would receive those via props and append add them to the injected `style` tags.

**Comment by sgratzl** [comment]
take a look at #98, it is a more generic approach which should cover your needs.
